###
# File: fluent-bit.s3-cold-storage.output.yaml
# Project: fluent-bit
# File Created: Tuesday, 29th October 2024 3:58:39 pm
# Author: Josh5 (jsunnex@gmail.com)
# -----
# Last Modified: Tuesday, 29th October 2024 4:18:27 pm
# Modified By: Josh5 (jsunnex@gmail.com)
###

# -- Custom config for S3 bucket cold storage added here --
